### ISSUE TITLE
Fix reference to Welcome image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5-repo-template#8]
Thanks for giving this a shot, @HeroicHitesh. Will you take another crack at it (see the message from the Welcome bot above)?

_Originally posted by @leecalcote in https://github.com/layer5io/layer5-repo-template/pull/7#issuecomment-717339377_

**Comment by HeroicHitesh** [comment]
@leecalcote I think the only way to resolve this issue is by using this format 
```
https://raw.githubusercontent.com/<username>/<repo-name>/master/.github/welcome/Layer5-celebration.png
```
But I am not sure how to get `username` and `repo-name` dynamically depending upon the place where this template repo is used. Any ideas on how we can do that in `config.yaml`

If implemented correctly, example for this repo - 
![pic](https://raw.githubusercontent.com/layer5io/layer5-repo-template/master/.github/welcome/Layer5-celebration.png)

**Comment by leecalcote** [comment]
@HeroicHitesh thanks for looking into this. We should be able to use a relative URL so that the link doesn't have to be updated each time.

**Comment by leecalcote** [comment]
@chinmaym07?
